version: '3.3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    read_only: true
    tmpfs:
      - /var/lib/postgresql/data

  redis:
    image: redis:alpine
    read_only: true
    tmpfs:
      - /data

  sqli:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
    command: |
      wait-for postgres:5432 -- python run.py
    read_only: true
    tmpfs:
      - /tmp
