name: Build & deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Cache modules
#         uses: actions/cache@v1
#         id: yarn-cache
#         with:
#           path: node_modules
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: ${{ runner.os }}-yarn-
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
#           aws-region: eu-west-1
#       - name: Use Node.js 12.x
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12.x
#       - name: Install dependencies
#         run: yarn

#       - name: Deploy
#         run: aws s3 sync ./suites/7926809735/artifacts s3://calab2
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Generate Report
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: cyclonedx.xml
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: cyclonedx.xml
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --recursive \
          --region eu-west-1 \
          ./build s3://calab2
