name: Mend Unified Agent Scan

on:
  push:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: pip install -r requirements.txt
      
    - name: Mend Unified Agent Scan
      env:
        WS_APIKEY: ${{secrets.APIKEY}}
        WS_USERKEY: ${{secrets.USERKEY}}
        WS_WSS_URL: https://saas-eu.mend.io/agent
        WS_PRODUCTNAME: GH_${{github.event.repository.name}}
        WS_PROJECTNAME: ${{github.ref}}_ghaction
      run: |
        echo Downloading Mend Unified Agent
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
          echo "Integrity Check Failed"
        else
          echo "Integrity Check Passed"
          echo Starting Mend Scan
          java -jar wss-unified-agent.jar
        fi
